drop table if exists users cascade;

CREATE TABLE users
(
    id         int8 generated by default as identity unique,
    username varchar(20),
    email varchar(20),
    password varchar(20),
    firstname varchar(20),
    lastname varchar(20),
    role_user varchar(20),
    keycloak_id varchar(20),
    primary key (id)
);
